#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

VENV="venv"

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi

"$PIP" install -U pip setuptools wheel
"$PIP" install -e ".[asyncio,trio,http2,socks]"
"$PIP" install coverage[toml] ruff mypy trio-typing pytest pytest-httpbin pytest-trio "werkzeug<3.1"
